app/urls.py
from django.urls import include,path
from django.contrib import admin
from app import views
from gografen import settings
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf.urls.static import static

urlpatterns = [
    # path('auth/users/activate/(?P<uid>[\w-]+)/(?P<token>[\w-]+)/$', UserActivationView.as_view()),
    path('', views.mainpage, name='main'),
    path('login_token',views.login_by_token,name='login_by_token'),
    path('home', views.home, name='home'),
    path('admin/', admin.site.urls ,name='admin'),
    path('comments/', views.allcomments, name='allcomments'),
    path('comments/<int:id>/', views.delcomment, name='delcomment'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('users/', views.users, name='users'),
    path('myhomeworks/', views.allhw, name='allhw'),
    path('myhomeworks/<int:id>/', views.hw, name='homework'),
    path('myhomeworks/add/', views.addhw, name='addhw'),
    path('myhomeworks/<int:id>/edit', views.edithw, name='edithomework'),
    path('myhomeworks/<int:id>/delete', views.delhw, name='deletehomework'),
    path('profile/', views.profile, name='profile'),
    path('users/delete/<int:id>/', views.deluser, name='deluser'),
    path('users/deleted/<int:id>/', views.delduser, name='delduser'),
    path('users/editeduser/<int:id>/', views.editeduser, name='editeduser'),
    path('users/edit/<int:id>/', views.edituser, name='edituser'),
    path('roles/', views.roles, name='roles'),
    path('roles/add/', views.addrole, name='addrole'),
    path('roles/delete/<int:id>/', views.delrole, name='delrole'),
    # path('roles/edit/<int:id>/', views.editrole, name='editrole'),
    path('roles/deleted/<int:id>/', views.deldrole, name='deldrole'),
    path('users/add/', views.adduser, name='adduser'),
    path('catalog/', views.catalog, name='catalog'),
    path('vectors/', views.vectors, name='vectors'),
    path('vectors/add/', views.addvector, name='addvector'),
    path('vectors/<int:id>/', views.vector, name='vector'),
    path('vectors/<int:id>/edit', views.editvector, name='editvector'),
    path('courses/', views.courses, name='courses'),
    path('mycourses/', views.mycourses, name='mycourses'),
    path('courses/add/', views.addcourse, name='addcourse'),
    path('courses/<int:id>/', views.course, name='course'),
    path('courses/<int:id>/edit', views.editcourse, name='editcourse'),
    path('courses/delete/<int:id>/', views.delcourse, name='delcourse'),
    path('courses/deleted/<int:id>/', views.deldcourse, name='deldcourse'),
    path('courses/<int:id>/add', views.addlesson, name='addlesson'),
    path('courses/<int:id>/buy', views.buy, name='buy'),
    path('courses/<int:id>/lesson/<int:l_id>', views.lesson, name='lesson'),
    path('courses/<int:id>/lesson/<int:l_id>/addhomework', views.homework, name='addhomework'),
    path('courses/<int:id>/lesson/<int:l_id>/exer_list', views.exersise_list, name='exer_list'),
    path('courses/<int:id>/lesson/<int:l_id>/exer_list/<int:e_id>/exer/', views.exersise, name='exercise'),
    path('courses/<int:id>/lesson/<int:l_id>/delete/', views.dellesson, name='dellesson'),
    path('courses/<int:id>/lesson/<int:l_id>/edit/', views.editlesson, name='editlesson'),
    path('courses/<int:id>/lesson/<int:l_id>/deleted/', views.deldlesson, name='deldlesson'),
    path('register/', views.register, name='register'),
    path('settings/', views.settings, name='settings'),
    # path('comments/', include('django_comments_xtd.urls')),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(r'^favicon.ico$', document_root='media/logo/favicon.ico')

gografen/urls.py
from datetime import datetime
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth.views import LoginView, LogoutView
from app import views
from gografen import views
from gografen import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.default,name="default"),
    path('admin/', admin.site.urls ,name='admin'),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # path("auth/", include("authentication.urls")),
    path('',include('app.routers')),
    # path('',views.wildcard_redirect),
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(r'^favicon.ico$', document_root='media/logo/favicon.ico')

app/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import Group,Permission
from django.core.exceptions import ValidationError

def validate_gografen(value): 
        if ".gografen.com" in value: 
            return value 
        else: 
            raise ValidationError("This field should have gogafen.com")

class SchoolSettingsChangeForm(forms.ModelForm):
    school_name = forms.CharField(max_length=100)
    sub_domen = forms.URLField(max_length=30,validators=[validate_gografen])
    school_logo_1 = forms.FileField()
    school_logo_2 = forms.FileField()
    
    class Meta:
        model=School 
        fields = ('school_name', 'sub_domen', 'school_logo_1','school_logo_2')

class CourseAddForm(forms.ModelForm):
    class Meta:
        model=Course 
        fields = ('title', 'cost', 'poster','mini_poster','short_desc', 'full_desc','end_date')

class VectorAddForm(forms.ModelForm):
    class Meta:
        model=Vector 
        fields = ('title','short_desc', 'creator_id')

class HomeworkAddForm(forms.ModelForm):
    class Meta:
        model=HomeWork 
        fields = ('title','desc', 'files','student_id','course_id','lesson_id')

class ExerciseAddForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields =('title','desc','text','creator_id','ex_id')

class Exercise_listAddForm(forms.ModelForm):
    class Meta:
        model = Exercise_list
        fields =('title','files','creator_id','lesson_id')

class LessonAddForm(forms.ModelForm):
    class Meta:
        model=Lesson 
        fields = ('title', 'files','video','short_desc','full_desc','duration','teacher_id','course_id')

class CommentAddForm(forms.ModelForm):
    class Meta:
        model=Comment 
        fields = ('content','user_id','course_id')

class LessonEditForm(forms.ModelForm):
    pass

class appUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30,error_messages={'name_length':"Слишком длинное имя"})
    email = forms.EmailField(error_messages={'email_exists':'Email exists'})
    phone = forms.CharField(max_length=20)
    
    class Meta:
        model=appUser 
        fields = ('username', 'password1', 'password2','first_name','email','phone')

class GroupCreationForm(forms.ModelForm):
    permissions = forms.MultipleChoiceField(label = "Права:", choices=Permission.objects.values_list('id', 'name'), widget = forms.CheckboxSelectMultiple)
    
    class Meta:
        model=Group 
        fields = ('name','description','permissions','school_id')

class GroupChangeForm(forms.ModelForm):
    permissions = forms.MultipleChoiceField(label = "Права:", choices=Permission.objects.values_list('id', 'name'), widget = forms.CheckboxSelectMultiple)
    
    class Meta:
        model=Group 
        fields = ('name','description','permissions')
 
class appUserAddingForm(UserCreationForm):
    role = forms.CharField(max_length=30)

    class Meta:
        model=appUser 
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'phone', 'role')

class appUserChangeForm(forms.ModelForm):
    class Meta:
        model=appUser 
        fields = ('first_name', 'last_name', 'phone', 'fathername','gender','birth_date','country')

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td scope="row"></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td scope="row"></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

{% endblock %}

app/templates/app/addrole.html
{% extends "app/layout.html" %}
{% with a=0 %}
{% endwith %}
{% block content %}
{% comment %} {{list}} {% endcomment %}
<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="addroleForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <hr />
                {% comment %} {{form.as_p}} {% endcomment %}
                {{form.errors}}
                <div class="form-group">
                    <input type="text" class="form-control d-none" name="school_id" id="id_school_id" placeholder="" value="{{user.school_id.id}}">
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <div class="input-group input-group-sm mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="id_name" id="basic-addon4">Роль:</label>
                            </div>
                            <input type="text" class="form-control  " name="name" maxlength="150"  required="" id="id_name"  aria-label="first name" aria-describedby="basic-addon4"> 
                        </div>
                        <div class="input-group input-group-sm mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="id_description" id="basic-addon5">Описание:</label>
                            </div>
                            <input type="text"  class="form-control  " name="description" maxlength="180"  required="" id="id_description"  aria-label="id_description" aria-describedby="basic-addon5"> 
                        </div>
                    </div>

                    <div class="col-md-offset-2 col-md-12">
                    {% comment %} {{list}} {% endcomment %}
                    
                            {% for pr,pe in list.items %}
                                {% comment %} {{pe}} {% endcomment %}
                                    <div class=" col-sm-6 ">
                                        {{pe.content_type}}
                                        <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                            <input type="checkbox" name="permissions" id="id_permissions_{{pr}}" value="{{pe.id}}" aria-label="Checkbox for following text input">
                                            </div>
                                        </div>
                                        <input type="text" class="form-control" disabled aria-label="Text input with checkbox" value="{{pe.name}}">
                                        </div>
                                    </div>
                            {% endfor %}
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" name="submit" value="Добавить роль" class="btn-save btn btn-primary" />
                    </div>
                </div>
            </form>
        
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}

<script>
$(document).ready(function() {
$('.mdb-select').materialSelect();
});
</script>
{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/addvector.html
{% extends "app/layout.html" %}

{% block content %}

<div class="container">
    <form action="" method="POST" class="form-horizontal">
        {% csrf_token %}
        <div class="col-md-offset-2 col-md-8">
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="id_title">Название:</label> 
                </div>
                <input type="text" name="title" maxlength="20" class="form-control" required="" id="id_title">
            </div>
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="id_short_desc">Краткое описание:</label>
                </div>
                <textarea class="form-control" name="short_desc" cols="40" rows="5" maxlength="200" id="id_short_desc"></textarea>
            </div>
            <div class="form-group">
                <input type="text" class="form-control d-none" name="creator_id" id="id_creator_id" placeholder="" value="{{user.id}}">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
</div>

{% endblock %}

app/templates/app/allcomments.html
{% extends "app/layout.html" %}

{% block content %}

<table class="table">
    <thead>
        <tr>
            <th>Отправитель</th>
            <th>Курс</th>
            <th>Коммент</th>
            <th>Время отправления</th>
            <th>Время изменения</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
{% for c in cc %}
        <tr>
            <td scope="row">{{c.user_id}}</td>
            <td><a href="{% url 'course' c.course_id.id %}">
                    {{c.course_id.title}}
                    </a>
            </td>
            <td>
            {{c.content}}</td>
            <td>{{c.pub_date}}</td>
            <td>{{c.change_date}}</td>
            
            <td>
                <a href="" type="button" class="btn btn-sm btn-outline-primary" data-href="delete.php?id=23" data-toggle="modal" data-target="#confirm-delete-{{forloop.counter}}">Действие</a>
            </td>
            <div class="modal fade" id="confirm-delete-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            Коммент от {{c.user_id}} | {{c.course_id.title}}
                        </div>
                        <div class="modal-body">
                            [{{c.pub_date}}] - {{c.content}}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                            {% comment %} <a name="" id="" class="btn btn-primary" href="#" role="button"></a> {% endcomment %}
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{forloop.counter}}" >Изменить</button>

                            <a href="{% url 'delcomment' c.id %}" class="btn btn-danger btn-ok">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </tr>
        <div class="modal fade" id="exampleModal-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Новый коммент</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control d-none" name="edit" id="edit" value="{{c.id}}" placeholder="">
                                <label for="message-text" class="col-form-label">Коммент:</label>
                                <textarea class="form-control" id="message-text" name="content">{{c.content}}</textarea>
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Изменить</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
{% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/app/course.html
{% extends "app/layout.html" %}

{% block content %}

<div class="container-fluid">
{% if user.id == course.creator_id.id or user.id == course.creator_id.school_id.creator_id.id %}
    <a name="" id="" class="btn btn-primary" href=" {% url 'courses' %}" role="button">Back</a>
{% else %}
    <a name="" id="" class="btn btn-primary" href=" {% url 'mycourses' %}" role="button">Back</a>
{% endif %}

    <div class="row">
        <div class="col-md-9">
            <div class="card text-center">
                <div class="card-header">
                    Курс:
                </div>
                <div class="card-body">
                    <h4 class="card-title">{{course.title}}</h4>
                    <p class="card-text">{{course.short_desc}}</p>
                </div>
                {% with lessons|first as first %}
                    {% if first %}
                        {% if access or user.id == course.creator_id.id or user.id == course.creator_id.school_id.creator_id.id %}
                            <a name="" id="" class="btn btn-primary" href="{% url 'lesson' course.id first.id %}" role="button">Начать</a>
                        {% else %}
                            <a name="" id="" class="btn btn-info" href="" role="button">Купить за {{course.cost}} тг</a>
                        {% endif %}
                    {% endif %}
                {% endwith %}
            </div>
            <form action="." method="POST">
                {% csrf_token %}
                <div class="coment-bottom bg-white p-2 px-4">
                    <div class="d-flex flex-row add-comment-section mt-4 mb-4">
                        <input type="hidden" name="user_id" value="{{request.user.id}}" />
                        <input type="hidden" name="course_id" value="{{course.id}}" />
                        <input type="text" name="content" class="form-control mr-3" placeholder="Add comment">
                        <button class="btn btn-primary" type="submit">Отправить</button>
                    </div>
                </div>
            </form>
            {% for c in comments %}
                <div class="coment-bottom bg-white p-2 px-4">
                    <div class="commented-section mt-2">
                        <div class="d-flex flex-row align-items-center commented-user">
                            <h5 class="mr-2">{{c.user_id.username}}</h5><span class="dot mb-1"></span>
                            <span class="mb-1 ml-2">{{c.pub_date}}</span>
                            <span class="mb-1 ml-2">{% if c.change_date %} изменён в {{c.change_date}} {% endif %} </span>
                            {% if c.user_id == user %}
                                <span class="mb-1 ml-5">
                                <a href="" type="button" class="btn btn-sm btn-outline-primary " data-href="delete.php?id=23" data-toggle="modal" data-target="#confirm-delete-{{forloop.counter}}">Изменить</a>
                                <a href="{% url 'delcomment' c.id %}" class="btn btn-danger btn-ok btn-sm">Удалить</a>
                                <div class="modal fade" id="confirm-delete-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                Коммент от {{c.user_id}} | {{c.course_id.title}}
                                            </div>
                                            <div class="modal-body">
                                                <form action="" method="POST">
                                                {% csrf_token %}
                                                <div class="form-group">
                                                    <input type="text" class="form-control d-none" name="edit" id="edit" value="{{c.id}}" placeholder="">
                                                </div>
                                                <div class="form-group">
                                                    <textarea class="form-control" name="content" id="id_content" rows="3">{{c.content}}</textarea>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                                <button type="submit" class="btn btn-primary">Изменить</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </span>
                            {% endif %}
                        </div>
                        <div class="comment-text-sm"><span>{{c.content}}</span></div>
                    </div>
                </div>
                
            {% endfor %}
        </div>
        <div class="col-md-3">
            <div class="card-header d-flex">
                Уроки:
                {% for perm in user.get_group_permissions  %}
                    {% if perm == 'app.add_lesson' %}
                        <a name="" id="" class="btn btn-primary ml-auto flex-row-reverse" href="{% url 'addlesson' course.id %}" role="button">Добавить</a>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="list-group">
                {% for l in lessons %}
                    <a 
                    {% if access or user.id == course.creator_id.id or user.id == course.creator_id.school_id.creator_id.id  %}
                        href="{% url 'lesson' course.id l.id %}" 
                    {% else %}
                        href="" 
                    {% endif %}
                    class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{l.title}}</h5>
                            <small>{{forloop.counter}}</small>
                        </div>
                        <p class="mb-1">{{l.duration}} мин</p>
                        <small>{{l.short_desc}}</small>
                    </a>
                {% endfor %}
            </div>
        </div>
        

    </div>
</div>

{% endblock %}

app/templates/app/register.html
{% comment %} {% extends "app/layout.html" %} {% endcomment %}
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
  <div class="container">

      <h2>{{ title }}</h2>
        <div class="row">
            <div class="col-md-8">
                <section id="registerForm">
                    <form action="." method="post" class="form-horizontal">
                        {% csrf_token %}
                        <h4>Use a local account to register.</h4>
                        <hr />
                        {{form.errors}}
                        {% comment %} {{form.as_p}} {% endcomment %}
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8">
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="id_username" id="basic-addon1">Имя пользователя:</label> 
                                    </div>
                                    <input type="text" class="form-control" name="username" maxlength="150" autofocus="" placeholder="username" aria-label="Username" required="" id="id_username" aria-describedby="basic-addon1">
                                    <span class="helptext form-text text-muted">Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.</span>
                                </div>
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="id_first_name" id="basic-addon4">Имя:</label>
                                    </div>
                                    <input type="text" class="form-control" name="first_name" maxlength="30"  required="" id="id_first_name" placeholder="first name" aria-label="first name" aria-describedby="basic-addon4"> 
                                </div>
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="id_phone" id="basic-addon31">Сотовый телефон:</label>
                                    </div>
                                    <input type="phone" class="form-control  " name="phone" maxlength="30"  required="" id="id_phone" placeholder="" aria-label="phone" aria-describedby="basic-addon31"> 
                                </div>
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="id_email" id="basic-addon6">Почта:</label>
                                    </div>
                                    <input type="email" class="form-control  " name="email" maxlength="30"  required="" id="id_email" placeholder="name@example.com" aria-label=" email" aria-describedby="basic-addon6"> 
                                </div>
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="id_password1" id="basic-addon2">Пароль:</label> 
                                    </div>
                                    <input type="password" class="form-control" name="password1" maxlength="150" autocomplete="new-password" required="" id="id_password1" placeholder="password" aria-label="password" aria-describedby="basic-addon2"> 
                                    <span class="helptext form-text text-muted" class="helptext"></span>
                                </div>
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="id_password2" id="basic-addon3">Подтверждение пароля:</label>
                                    </div>
                                    <input type="password" class="form-control  " name="password2" maxlength="150" autocomplete="new-password" required="" id="id_password2" placeholder="confirm password" aria-label="password" aria-describedby="basic-addon3"> 
                                    <span class="helptext form-text text-muted w-100" class="helptext">Для подтверждения введите, пожалуйста, пароль ещё раз.</span>
                                </div>
                            </div>
                            
                            <div class="col-md-8">
                                <ul><li>Your password can’t be too similar to your other personal information.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul><p></p>
                            </div>

                        </div>
                        <hr />
                        <div class="form-group row">
                            <div class="col-md-offset-2 col-md-2">
                                <input type="hidden" name="next" value="/" />
                                <input type="submit" name="submit" value="Sign up" class="btn btn-warning" />
                            </div>
                        </div>
                    </form>
                
                </section>
            </div>
            <div class="col-md-4">
                <section id="socialLoginForm"></section>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>
{% block content %}


{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}